# Site settings
author: Dallas Blackwell
title: My Journey as a Software Engineer
header-img: img/home-bg.png
email: mdvayne923@gmail.com
copyright_name: Dallas Blackwell
description: > # this means to ignore newlines until "baseurl:"
  Challenges Underneath the Goal 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DallasBlackwell

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
